### PR TITLE
Merged with your BBB changes

### PR DESCRIPTION
**Pull request by drewengelmann**
Hi Sean,

I have merged my repo with your BBB changes, canceled the original pull request and submitted this pull request. A couple of notes:
1) This pull request is still being flagged as "can't automatically merge". I don't think there are any real conflicts. I did move all of the test dma code to a separate function to keep main() clean for testing. 
2) The nrf_read_reg function still doesn't use the reg argument. Are you fixing this? 

-Drew

### CODE REVIEW

**Comment by seanrivera** [comment]
Yeah I'm fixing it. Have limited access to Internet right now. Will push when I get better access.

Can you try to pull from my repo and see what merge conflicts

**Comment by drewengelmann** [comment]
Hi Sean,
The conflicts are trivial. There are all whitespace except for main.c, and for that one I moved all the of the test variables for the memory/DMA tests to test_dma.c. I have enclosed screen shots of all the conflicts. 
I'm going to start on the report tonight. 
-Drew  

    On Wednesday, August 3, 2016 5:12 PM, Sean Rivera <notifications@github.com> wrote:
 

 Yeah I'm fixing it. Have limited access to Internet right now. Will push when I get better access.Can you try to pull from my repo and see what merge conflicts —

**Comment by drewengelmann** [comment]
I forgot to attach the screenshots. 
-Drew 

    On Wednesday, August 3, 2016 7:42 PM, Scooby Drew <scooby.drew@yahoo.com> wrote:
 

 Hi Sean,
The conflicts are trivial. There are all whitespace except for main.c, and for that one I moved all the of the test variables for the memory/DMA tests to test_dma.c. I have enclosed screen shots of all the conflicts. 
I'm going to start on the report tonight. 
-Drew  

    On Wednesday, August 3, 2016 5:12 PM, Sean Rivera <notifications@github.com> wrote:
 

 Yeah I'm fixing it. Have limited access to Internet right now. Will push when I get better access.Can you try to pull from my repo and see what merge conflicts —

**Comment by seanrivera** [comment]
So I finished merging it in. Let me know when you are done with the report so I can add my stuff

**Comment by drewengelmann** [comment]
Hi Sean,
I'll finish the report tomorrow morning and push it to your repo. I'll have about 4 hours to finish everything before I go out of town Thur afternoon.
-Drew 

    On Wednesday, August 3, 2016 10:45 PM, Sean Rivera <notifications@github.com> wrote:
 

 So I finished merging it in. Let me know when you are done with the report so I can add my stuff—

**Comment by seanrivera** [comment]
Cool

**Pull request merged**
